title: "준민아빠의 블로그"    # 블로그 제목
description: "개발자로 살아가는 준민아빠의 기록"  # 간단 소개
#theme: minima

highlighter: pygments

# 글 링크 형태 (선택)
permalink: /:year/:month/:day/:title/

header_pages:
  - index.md
  - posts.md
  #- about.md
